// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortLink.DAL.Data;

#nullable disable

namespace ShortLink.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250129152350_CreateNewPropertyInShortUrl")]
    partial class CreateNewPropertyInShortUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShortLink.Domain.Entities.OriginalUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OriginalUrls");
                });

            modelBuilder.Entity("ShortLink.Domain.Entities.ShortUrl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OriginalUrlId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalUrlId");

                    b.ToTable("ShortUrls");
                });

            modelBuilder.Entity("ShortLink.Domain.Entities.ShortUrl", b =>
                {
                    b.HasOne("ShortLink.Domain.Entities.OriginalUrl", "OriginalUrl")
                        .WithMany()
                        .HasForeignKey("OriginalUrlId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
